[package]
name = "binary_timehash"
version = "0.1.0"
authors = ["mriise <mark.riise26@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
